metrics:
  cpu_times:
    display: true
    time: 1
    split:
      user: true
      system: false
      idle: false

  cpu_percent:
    display: true
    percpu: true
    time: 1
  cpu_times_percent:
    display: false
    time: 4

config:
  monitored_server: back_end
  influxdb_url: http://192.168.64.9:8086
  influxdb_token: -7oALy0GcWUTEHyJTddYOWtzjskFaG93sldnjO47VM7XjxRzuKcBQOxt_e8eh9Q37f0x7FRvNqdJZ6UdOBfVuw==
  influxdb_org: coding
  influxdb_bucket: movie_logs
