metrics:
  cpu_times:
    display: true
    time: 5

  cpu_percent:
    display: true
    time: 5

  cpu_times_percent:
    display: false
    time: 5

  cpu_count:
    display: true
    time: 5

  cpu_freq:
    display: true
    time: 5

  cpu_stats:
    display: false
    time: 5

  cpu_times_percent:
    display: true
    time: 5

  cpu_times_percent_windows:
    display: false
    time: 5

  cpu_count_logical:
    display: true
    time: 5

  cpu_count_physical:
    display: true
    time: 5

  cpu_percent_per_cpu:
    display: true
    time: 5


config:
  monitored_server: back_end
  influxdb_url: http://192.168.64.9:8086
  influxdb_token: -7oALy0GcWUTEHyJTddYOWtzjskFaG93sldnjO47VM7XjxRzuKcBQOxt_e8eh9Q37f0x7FRvNqdJZ6UdOBfVuw==
  influxdb_org: coding
  influxdb_bucket: movie_logs
