metrics:
  cpu_times:
    display: false
    time: 10

  cpu_percent:
    display: false
    time: 10

  cpu_times_percent:
    display: false
    time: 10

  cpu_count:
    display: false
    time: 10

  cpu_stats:
    display: false
    time: 10

  getloadavg:
    display: false
    time: 10

  virtual_memory:
    display: true
    time: 10

  swap_memory:
    display: false
    time: 10

  disk_partitions:
    all: false
    display: false
    time: 10

  disk_usage:
    display: false
    time: 10
    path: "/"

  net_io_counters:
    display: false
    time: 10

  net_connections:
    display: false
    time: 10

  net_if_addrs:
    display: false
    time: 10

  net_if_stats:
    display: false
    time: 10

  sensors_battery:
    display: false
    time: 10

  boot_time:
    display: false
    time: 10

  users:
    display: false
    time: 10

  process_iter:
    display: false
    time: 10

config:
  monitored_server: back_end
  influxdb_url: http://192.168.64.12:8086
  influxdb_token: 5akShSOR813MQmv7ZehBxLF97KbvDPFOWL-R15TrTCcnUVOhtYQ_w6OAiVkfcRilWY07m1iMa5XHqpUWlYZIMw==
  influxdb_org: coding
  influxdb_bucket: movie_logs
