metrics:
  cpu_times:
    display: true
    time: 5

  cpu_percent:
    display: true
    time: 5

  cpu_times_percent:
    display: true
    time: 5

  cpu_count:
    display: true
    time: 5

  cpu_stats:
    display: true
    time: 5

  getloadavg:
    display: true
    time: 5

  virtual_memory:
    display: true
    time: 5

  swap_memory:
    display: true
    time: 5

  disk_partitions:
    all: true
    display: true
    time: 5

  disk_usage:
    display: true
    time: 5
    path: "/"

  net_io_counters:
    display: true
    time: 5

  net_connections:
    display: true
    time: 5

  net_if_addrs:
    display: true
    time: 5

  net_if_stats:
    display: true
    time: 5

  sensors_battery:
    display: true
    time: 5

  boot_time:
    display: true
    time: 5

  users:
    display: true
    time: 5

  process_iter:
    display: true
    time: 5

config:
  monitored_server: back_end
  influxdb_url: http://192.168.64.12:8086
  influxdb_token: 5akShSOR813MQmv7ZehBxLF97KbvDPFOWL-R15TrTCcnUVOhtYQ_w6OAiVkfcRilWY07m1iMa5XHqpUWlYZIMw==
  influxdb_org: coding
  influxdb_bucket: movie_logs
